on: 
  push: 
    branches: 
      - master

name: Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy via SSH
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        flags: '-avzr --delete'
        options: ''
        ssh_options: ''
        src: ''
        dest: 'ibrecem@tp.web76111.kinghost.net:/home/ibrecem/www/wp-content'