on: 
  push: 
    branches: 
      - master

name: Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy via SSH
      uses: easingthemes/ssh-deploy@v2.0.7
      with:
        ARGS: -avzr --delete
        SOURCE: /
        TARGET: /www/wp-content
        REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.DEPLOY_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}