on: 
  push: 
    branches: 
      - master

name: Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy via SSH
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        ARGS: -avzr --delete
        SOURCE:
        REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.DEPLOY_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        TARGET: /home/ibrecem/www/wp-content