name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy WordPress
    runs-on: ubuntu-latest
    steps:
    - name: Deploy WordPress
      uses: rtCamp/action-deploy-wordpress@v1.0.0
